- name: mongodb
  hosts: mongodb
  become: yes
  tasks:
  - name: copy mongodbrepo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

  - name: istall mongodb
      ansible.builtin.package:
        name: mongodb-org
        state: present

  - name: start and enable mongdb
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

  - name: allow remote connections
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
   - name: resatrt mongdb
      ansible.builtin.service:
        name: mongod
        state: restarted